# все поля для API-запросов socialnetwork.api.workgroup.get и socialnetwork.api.workgroup.list
SELECT_FIELDS = ("ID", "ACTIVE", "SITE_ID", "SUBJECT_ID", "SUBJECT_DATA", "NAME", "DESCRIPTION", "KEYWORDS", "CLOSED", "VISIBLE",
                 "OPENED", "PROJECT", "LANDING", "DATE_CREATE", "DATE_UPDATE", "DATE_ACTIVITY", "IMAGE_ID", "AVATAR",  "AVATAR_TYPE", "AVATAR_TYPES",
                 "OWNER_ID", "OWNER_DATA", "NUMBER_OF_MEMBERS", "NUMBER_OF_MODERATORS", "INITIATE_PERMS", "PROJECT_DATE_START",
                 "PROJECT_DATE_FINISH", "SEARCH_INDEX", "SCRUM_OWNER_ID", "SCRUM_MASTER_ID", "SCRUM_SPRINT_DURATION",
                 "SCRUM_TASK_RESPONSIBLE", "TYPE", "UF_SG_DEPT", "TAGS", "ACTIONS", "USER_DATA")
