# Generated by Django 5.1.7 on 2025-11-28 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('error_place', models.TextField(verbose_name='Где произошла ошибка')),
                ('error_desc', models.TextField(verbose_name='Описание ошибки')),
                ('error_level', models.TextField(choices=[('error', 'error'), ('warning', 'warning'), ('info', 'info')], verbose_name='Уровень ошибки')),
            ],
        ),
    ]
