# Generated by Django 5.1.7 on 2025-11-29 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_logger', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Logs',
            new_name='Log',
        ),
    ]
