# Generated by Django 4.1.13 on 2026-01-29 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_logger', '0002_rename_logs_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='traceback',
            field=models.TextField(blank=True, null=True, verbose_name='Traceback'),
        ),
    ]
